# Generated by Django 4.1.1 on 2023-04-23 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancy', '0002_alter_resume_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Vacancy',
        ),
    ]
